# base settings
set -s escape-time 0
set -g mouse on
set -g allow-passthrough all
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -g focus-events on

# key bindings
set -wg mode-keys vi

## prefix (^T)
unbind C-b
set -g prefix ^T
bind r source-file ~/.tmux.conf\; display-message "Reload Config!!"

# index
set -g base-index 0
set -g pane-base-index 0

# colors
set -g default-terminal "screen-256color"
set -g pane-border-style fg="colour245"
set -g pane-active-border-style fg="colour39"
set -g pane-border-status off
set -g pane-border-format " #P: #{b:pane_current_path} "
set -g display-panes-time 5000

# status line
set -g status-style fg="white",bg="colour234"
set -g status-interval 1
set -g status-left-length 32
set -g status-left '#[fg=cyan] #h |'
set -g window-status-format " #I #W #F "
set -g window-status-current-format "#[fg=green,bg=colour237,bold] #I #W #F "
set -g status-right-length 150
set -g status-right '#[fg=colour244]%Y/%m/%d %H:%M:%S '
set -g message-style "bold",fg="white",bg="red"

# rename
set -wg automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'

# window
bind enter resize-pane -Z
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind j next-window
bind k previous-window
bind BSpace previous-window
bind / split-window -h \; split-window -h \; select-layout even-horizontal
bind s set-window-option synchronize-panes \; display-message "synchronize-panes: #{?pane_synchronized,on,off}"

bind A command-prompt "rename-window %%"
bind ^t last-window
bind K confirm-before "kill-window"
bind w display-popup -w 60% -h 40% -E "\
  target=\$(tmux list-windows -F '#I: #W' | fzf --height 100% --reverse | cut -d ':' -f 1) && \
  if [ -n \"\$target\" ]; then tmux select-window -t \"\$target\"; fi"
bind p display-popup -w 80% -h 60% -d '#{pane_current_path}' -E \
  "printf '' | pbcopy; file=\$(fd -i --type file | fzf --height 100% --reverse) && printf '%s' \"\$file\" | pbcopy; true" \;\
  run-shell "file=\$(pbpaste); [ -n \"\$file\" ] && tmux send-keys -t '#{pane_id}' \"\$file\"; true"

# panes
bind l select-pane -R
bind h select-pane -L
bind u select-pane -U
bind m select-pane -D
bind Tab select-pane -t:.+
bind BTab select-pane -t:.-
bind -n M-Right resize-pane -R 3
bind -n M-Left  resize-pane -L 3
bind -n M-Up    resize-pane -U 3
bind -n M-Down  resize-pane -D 3
bind -n M-0 select-pane -t 0
bind -n M-1 select-pane -t 1
bind -n M-2 select-pane -t 2
bind -n M-3 select-pane -t 3
bind -n M-4 select-pane -t 4
bind -n M-5 select-pane -t 5
set-hook -g window-layout-changed 'if-shell "[ #{window_panes} -gt 1 ]" "set -w pane-border-status top" "set -w pane-border-status off"'

# session
bind ^D detach
bind * list-clients
bind -n S-Enter send-keys Escape "[13;2u"
bind g popup -w90% -h90% -d '#{pane_current_path}' -E tig
