cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "universal-ctags/universal-ctags"

brew "bitwarden-cli"
brew "colordiff"
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "fd"
brew "fzf"
brew "git"
brew "gh"
brew "ghq"
brew "git-delta"
brew "gnupg"
brew "glow"
brew "hub"
brew "jq"
brew "jnv"
brew "keychain"
brew "mas"
brew "mise"
brew "nkf"
brew "ripgrep"
brew "tig"
brew "tmux"
brew "tree"
brew "universal-ctags", args: ["HEAD"]
brew "vim"
brew "watch"
brew "wget"
brew "zsh"

cask "aws-vault"
cask "font-hackgen"
cask "font-udev-gothic"
cask "ghostty"
cask "google-chrome"
cask "google-japanese-ime"
cask "obsidian"
cask "qlmarkdown"
cask "raycast"
cask "visual-studio-code"

mas "Bitwarden", id: 1352778147
mas "Display Menu", id: 549083868
mas "CotEditor", id: 1024640650
mas "The Unarchiver", id: 425424353
